# -*- coding: utf-8 -*-
"""EVEN ODD DETECTOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hdO8ub8WcXdZw2fNKCSoixJl2DvM_mYg
"""

while True:
 x = float(input('Enter integer to detect if it is even or odd x= '))
 a = int(x)
 b = float(x)
 if not a == b:
  print('Neither even nor odd (error: Number must be integar)')
  break
 elif a%2 == 0:
  print('even')
 else:
  print('odd')
  #JR